### ISSUE TITLE
Sabers vanish after the song completes

### ISSUE THREAD

**Issue by eternaldensity** [NeoSpark314/BeepSaber#1]
You have a perfectly usuable hide method for the sabers which you're not using.  Currently you're setting the sabers' visibility to false when the menu is brought up in show_menu() after the song is finished.  Instead do this:

```
		_main_menu.set_mode_game_start();
		left_saber.hide();
		right_saber.hide();
```
Otherwise the sabers go away completely and never come back.

**Comment by NeoSpark314** [comment]
Thank you! Just added this fix... but this triggers now the hide animation also when starting the game... I will look into this later :-)

**Comment by eternaldensity** [comment]
Ah, looks like the problem is that when the menu is first shown, the
QuickHide animation has not yet moved the sabers into a position that
counts as not extended, so the Hide animation is played.

Changing the hide condition to
```
if (is_extended() and _anim.current_animation != "QuickHide"):
```
fixes that

**Comment by NeoSpark314** [comment]
Nice; fixed it; thanks a lot for digging through the code! :-)

**Comment by eternaldensity** [comment]
No worries.

BTW I've got it loading playlists and maps from the Downloads folder if
you're interested in seeing my code for that.

**Comment by NeoSpark314** [comment]
Nice; that would have been the next thing I wanted to add. Feel free to open a pull request for your changes.
